#Springboot启动端口
server:
  port: 8080

#ActiveMQ配置
spring:
  activemq:
    broker-url: tcp://zookeeper00:61616 #ActiveMQ服务器IP
#    broker-url: nio://zookeeper00:61608 #nio协议连接
    user: admin #ActiveMQ连接用户名
    password: admin #ActiveMQ连接密码
  jms:
    #指定连接队列还是主题
    pub-sub-domain: true # false = Queue |  true = Topic


#定义服务上的队列名
my:
  topic:
    name: springboot-activemq-topic